GET http://localhost:3000/orders

###
POST  http://localhost:3000/orders
Content-Type: application/json

{
    "asset_id" : "asset 4"
    ,"price": 15.0
    //,"status": "open"
}


###
GET http://localhost:3000/assets

###
POST http://localhost:3000/assets
Content-Type: application/json

{
    "id":"asset 3",
    "symbol":"ASSET 3"
}


